Repository cedricr/100joursdezbeul, pull requests merged in 2023-05, with the labels that each got.

#105 Fix CSS Flexbox de la liste des évènements
  src/lib/event.svelte
Labels: bug, a11y

#102 Menu + lien d'accès rapide au contenu principal
  src/routes/+layout.svelte
Labels: enhancement, a11y

#123 Augmente la taille du texte
  src/lib/event.svelte
Labels: enhancement, good first issue, design, a11y

#32 feat: national statistics
  src/lib/utils.ts
  src/routes/+page.svelte
  src/routes/plan-site/+page.svelte
  src/routes/statistiques/+page.svelte
Labels: enhancement, good first issue, design, dev

#126 Ajout des réseaux sociaux du syndicat
  src/routes/+layout.svelte
  src/routes/footer.svelte
Labels: enhancement, good first issue, a11y

#117 Add hover effet on row
  src/app.postcss
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/presse/+page.svelte
Labels: enhancement
