Repository cedricr/100joursdezbeul, pull requests merged in 2023-04, with the labels that each got.

#44 Ajout de l'image d'en-tête, badges et formattage
  README.md
Labels: documentation

#49 Fix du rang
  src/routes/+page.svelte
Labels: bug, a11y

#19 Ajout d'une page presse
  src/lib/assets/media-refs.json
  src/lib/utils.ts
  src/routes/+page.svelte
  src/routes/presse/+page.svelte
  static/media/actu.fr.png
  static/media/bfmtv.png
  static/media/francebleu.png
  static/media/humanite.jpg
  static/media/lemedia.jpg
  static/media/mediapart.png
  static/media/oziol.jpg
  static/media/radioscoop.ico
  static/media/readme.md
  static/media/regards.png
Labels: enhancement, design, dev

#64 Fix equality podium case
  src/routes/+page.svelte
Labels: bug, good first issue

#46 try to manage oe digram from nextcloud
  scripts/updateData/utils/data.util.js
Labels: bug, data

#78 Médailles SVG
  src/lib/assets/icons/medaille-argent.svg
  src/lib/assets/icons/medaille-bronze.svg
  src/lib/assets/icons/medaille-or.svg
  src/routes/+page.svelte
Labels: enhancement, a11y
